services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    init: true
    volumes:
      - .:/home/user/.mgpm
      - target_volume:/home/user/.mgpm/target

volumes:
  target_volume:
